### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by knightmeister** [MicrosoftDocs/winui-api#10]
The documentation has no relevance to the property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8802ff-e9be-5a85-7c04-c6670e0cb4ef
* Version Independent ID: eec9e6b8-b647-6d72-752d-2570322df741
* Content: [NavigationView.IsTitleBarAutoPaddingEnabled Property - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.istitlebarautopaddingenabled#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mikehillberg put out a PR for this I think.

**Comment by Karl-Bridge-Microsoft** [comment]
PR corrected this.
