### ISSUE TITLE
Dependency property binding failure

### ISSUE THREAD

**Issue by cpehonk** [MicrosoftDocs/winui-api#105]
Consider following situation: one scrollbar controls the position of e.g. three scrollable controls. This is done via a property of a view model implementing "INotifyPropertyChange". The scrollbar uses "TwoWay" mode for the value of the scrollbar => works fine. The "consuming" controls only bind mode "OneWay" on the same property of the view model => does NOT work! Only binding in mode "TwoWay" for all controls works. Is this a bug or a feature ?
Greetings
Christoph

**Comment by cpehonk** [comment]
Forgot to tell you the environment: VS 2022, Latest Winui 3 SDK, .Net 6

**Comment by Karl-Bridge-Microsoft** [comment]
As this isn't a specific doc issue, please file an issue/bug at official https://github.com/microsoft/microsoft-ui-xaml repo.
