### ISSUE TITLE
The snippet for the multi-thread windows is incorrect and also has a typo

### ISSUE THREAD

**Issue by mattleibow** [MicrosoftDocs/winui-api#107]
The code snippet is incorrect because it uses a parameterless constructor for `DispatcherQueueSynchronizationContext` which does not exist.

It also has a typo with `DispatcherQueueSyncronizationContext` missing the `h` in "synchronization".

> To create a new Window on a new thread in a Desktop app, create the thread first and then use the DispatcherQueueSynchronizationContext to queue work to another thread.

```cs
var thread = new Thread(() =>
{
    Window window = new Window();
    window.Content = new TextBlock() { Text = "Hello" };
    window.Activate();
    window.Closed += (_, __) => w.DispatcherQueue.InvokeShutdown();

    var syncContext = new DispatcherQueueSyncronizationContext();
    SynchronizationContext.SetSynchronizationContext(syncContext);

    this.ProcessEvents(); // Message pump
});

thread.SetApartmentState(ApartmentState.STA);
thread.Start(); 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c683f28d-2b9c-0641-3781-4fe778715757
* Version Independent ID: 5ed66529-4e1d-a4b5-4f13-278ed139ff07
* Content: [Window Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by mattleibow** [comment]
This issue is almost the same as #64 but that was closed without a resolution.

**Comment by Karl-Bridge-Microsoft** [comment]
As suggested by the product team, this section has been deleted.

Multi window on a single thread is supported, but on multiple threads is not.
