### ISSUE TITLE
DataTemplateSelector docs don't show a complete example

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#109]
There's not a complete example of creating a `DataTemplateSelector` here in the docs. The linked docs don't show one either.

It should link to this page: https://docs.microsoft.com/windows/apps/design/controls/data-template-selector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd31a6f6-9d0f-d7fa-8e11-84164a543e93
* Version Independent ID: 92bcb050-2aa9-5b74-8066-7ab2fb2987cc
* Content: [DataTemplateSelector Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.datatemplateselector?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/DataTemplateSelector.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/DataTemplateSelector.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks. Links to Data template selection article have been added.
