### ISSUE TITLE
Related links to get command line arguments

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#110]
Since the Arguments property isn't supported, there should be references to the [GetCommandLine](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea) function (for C++) and [Environment.GetCommandLineArgs](http://msdn.microsoft.com/library/System.Environment.GetCommandLineArgs) (for C#) APIs as alternatives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca64572-d0d3-9504-b215-9b5572a44f5b
* Version Independent ID: 5a6428b1-4dc9-2bba-eeac-7a886d074ed3
* Content: [LaunchActivatedEventArgs Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.launchactivatedeventargs?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/LaunchActivatedEventArgs.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/LaunchActivatedEventArgs.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @MikeHillberg - references added to Remarks section
