### ISSUE TITLE
Win UI 3.0 - Setting The Title Attribute Of The Window Element In XAML Doesn't Work

### ISSUE THREAD

**Issue by riccardo10** [MicrosoftDocs/winui-api#111]
The sample code in the documentation which demonstrates setting the Title attribute of the Window element is misleading.

The Title attribute of the Window element in the xaml file is recognised by the IntelliSense but not by the xaml processor and produces the error code **WMC061** when attempting to build.

The error description is : 

> The XAML Binary Format (XBF) generator reported syntax error '0x09C4': Property Not Found

As a workaround, I have had to set the Title property in the code-behind file.

I am using Visual Studio 2019 Professional Edition version 16.11.13.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d6220d7-0b11-f599-3623-4c88d2495063
* Version Independent ID: 935840a7-a95d-55dd-d721-d593ae02ae5f
* Content: [Window.Title Property (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.title?view=winui-3.0#feedback)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
This issue is fixed in Windows App SDK 1.3.1 and later. The docs are updated to indicate this.
