### ISSUE TITLE
ProtectedCursor needs to be updated once control is in Visual Tree

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#112]
See Issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/7062

If you try and modify the ProtectedCursor in the initialization of a control before OnApplyTemplate has been called, then this will cause a crash.

We should add a warning/note here in the docs about this for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f75a21-bfcc-6936-51d6-bb48431a2db7
* Version Independent ID: 6dfcc512-d060-84df-4bf2-1fc7f2f946d5
* Content: [UIElement.ProtectedCursor Property (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.protectedcursor?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/UIElement.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @michael-hawker - reviewing long lost issues... According to 7062: This crash is fixed in 1.4-preview1 and was also serviced to 1.3 in 1.3.230602002. Closing.
