### ISSUE TITLE
Incorrect sample code on PointerRoutedEventArgs

### ISSUE THREAD

**Issue by Shailosingh** [MicrosoftDocs/winui-api#113]
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.pointerroutedeventargs?view=winui-3.0

In this article, it explains how one can use PointerRoutedEventArgs to get various pieces of information about the pointer and do different tasks. The article is mostly good but, has one glaring problem

![image](https://user-images.githubusercontent.com/52577016/167080760-21ce2bfa-8867-438e-ab39-13682901d394.png)

In most lines of code, "Windows.UI.Xaml.Input..." is used. However, for this piece of documentation, it is wrong. Both e.pointer and e.GetCurrentPoint(Target) return types from "Microsoft.UI.Xaml.Input..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604ea511-cf47-0688-4999-aa507ca00fa4
* Version Independent ID: 4d517ee9-a95a-d21c-ce5b-ddf733a79151
* Content: [PointerRoutedEventArgs Class (Microsoft.UI.Xaml.Input) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.pointerroutedeventargs?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Input/PointerRoutedEventArgs.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Input/PointerRoutedEventArgs.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This topic has moved to the WinApp SDK ref doc set: https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs?view=windows-app-sdk-1.1

Snippet has been updated.
