### ISSUE TITLE
Dead link in ListView

### ISSUE THREAD

**Issue by kostya9** [MicrosoftDocs/winui-api#116]
[ListView](https://github.com/MicrosoftDocs/winui-api/blob/docs/microsoft.ui.xaml.controls/listview.md) Page

The [link](https://github.com/MicrosoftDocs/winui-api/blob/docs/windows/apps/debug-test-perf/optimize-gridview-and-listview) in the following section

> If you use the ListView to display large sets of data, see [Optimize ListView and GridView](https://github.com/MicrosoftDocs/winui-api/blob/docs/windows/uwp/debug-test-perf/optimize-gridview-and-listview) for tips to maintain a smooth and responsive user experience.

is pointing to a missing page

**Comment by jwmsft** [comment]
Link appears to be fixed.
