### ISSUE TITLE
ItemsRepeater Remarks section links should direct to Microsoft.UI.Xaml namespace docs but go to Windows.UI.Xaml instead.

### ISSUE THREAD

**Issue by dPJinjo** [MicrosoftDocs/winui-api#137]
In the Remarks section [here](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemsrepeater.itemtemplate?view=winui-2.8#remarks) the links for DataTemplate and DataTemplateSelector navigate to the Windows.UI.Xaml namespace documentation when I think it would be better to navigate to the Microsoft.UI.Xaml versions to best help readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab12df5-c193-8425-aa46-363e24bfea3d
* Version Independent ID: 60070c66-9576-2d70-0728-c557b2a8caf1
* Content: [ItemsRepeater.ItemTemplate Property (Microsoft.UI.Xaml.Controls) - WinUI](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemsrepeater.itemtemplate?view=winui-2.8#microsoft-ui-xaml-controls-itemsrepeater-itemtemplate)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/ItemsRepeater.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/ItemsRepeater.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Since the WinUI 2 and WinUI 3 reference docs have been separated, each version points to the correct place. The [WinUI 3 version](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.itemsrepeater.itemtemplate) points to Microsoft.UI.Xaml.
