### ISSUE TITLE
Where can we find the AcrylicBrush class that works with Windows Toolkit 6?

### ISSUE THREAD

**Issue by Jeff4rr** [MicrosoftDocs/winui-api#14]
I'm getting messages that AcrylicBrush is not compatible with Microsft.Toolkit.Xaml.UI.Controls version 6, telling me I need 5.1.1 which does not work with 1903....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1e35d9-6985-3ca4-5019-36757bfd0559
* Version Independent ID: 3186e76f-aaa0-b399-3574-75d70c47033b
* Content: [AcrylicBrush Constructor - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.media.acrylicbrush.-ctor?view=winui-2.3#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.media.acrylicbrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.media.acrylicbrush.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by michael-hawker** [comment]
@Jeff4rr can you provide more details about the specific error message you're seeing and how your project/environment is setup? 

This sort of sounds like an issue with referencing different versions of NuGet packages across different projects.  The toolkit 5.1.1 or 6.0.0 should work fine with 1903 in either case, and should be able to work with WinUI 2.x.

**Comment by Jeff4rr** [comment]
@michael-hawker - User error - Acrylic Brush is working with Toolkit 6, Control using brush had other errors.
