### ISSUE TITLE
No documentation for class IndexPath and it's methods

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winui-api#25]
Currently there is no description for the IndexPath class and none of the methods have any documentation on what they do.

I haven't found the corresponding API review on [microsoft-ui-xaml-specs](https://github.com/microsoft/microsoft-ui-xaml-specs), so my question would be if there is a document for this or would one have to write that from scratch?

In the latter case, I would love to write the docs for that class if that's fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eacc4e94-2f8f-c71a-3313-6444faaf41bb
* Version Independent ID: fcf52f35-2a75-52f8-2416-4074d89360f3
* Content: [IndexPath Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.indexpath?view=winui-2.4)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/IndexPath.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/IndexPath.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by MikeHillberg** [comment]
Thank you! This is still in Preview, the first step when we're ready is an API spec, and when that's complete we can copy the content here. Adding @ranjeshj, I'm not sure what the timing is.

**Comment by ranjeshj** [comment]
Yep. This is still in preview and getting validated now through usage in NavigationView. We need to create a spec and go through the API review process. @anawishnoff as FYI.

**Comment by Karl-Bridge-Microsoft** [comment]
The WinUI 2.5 pre-release docs have been published. However, only docs for the stable/official releases of WinUI 2.x need to be fully documented with descriptions and other details. 

Pre-release docs do not require anything other than basic stubs with the automated info provided by our publishing platform.

Once the docs for the official WinUI 2.5 package have been published, you are more than welcome to contribute to them.
