### ISSUE TITLE
RevealListViewItemPresenter does not have class description

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winui-api#26]
In contrast to the [WUXC ListViewItemPresenter](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.listviewitempresenter), the RevealListViewItemPresenter class has almost no documentation.

This is something we should change. Is that class the replacement for the WUXC ListViewItemPresenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5328dc0e-a96c-5669-494f-1a7e7527509d
* Version Independent ID: 8f84d39f-17a7-c652-fe64-c3d0a8307608
* Content: [RevealListViewItemPresenter Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.reveallistviewitempresenter?view=winui-2.4)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/RevealListViewItemPresenter.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/RevealListViewItemPresenter.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @chingucoding - finally getting around to updating this topic. I've added a description and note that indicates the control is no longer necessary and ListViewItemPresenter should be used instead (if possible).

**Comment by marcelwgn** [comment]
Great to hear that, thank you! I assume the updated description will be available in the next few days then?

**Comment by Karl-Bridge-Microsoft** [comment]
Should be live soon.

**Comment by marcelwgn** [comment]
Awesome!
