### ISSUE TITLE
invalid link to Scroller

### ISSUE THREAD

**Issue by rectified95** [MicrosoftDocs/winui-api#28]
The hyperlinks that are supposed to lead to a page on Scroller result in the the HTTP 404 error code being returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6ac62e-08b0-f39a-8ac4-e64442e70f5b
* Version Independent ID: 7c595f03-e6fd-13c7-c8b5-38ee662ca8e3
* Content: [ScrollViewer.ScrollerProperty Property (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.scrollviewer.scrollerproperty?view=winui-2.4#feedback)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/ScrollViewer.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/ScrollViewer.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
The WinUI 2.5 pre-release docs have been published, which I think will fix this issue. Please file a new issue if this is not the case. Thanks.
