### ISSUE TITLE
Should have a link in see also to the ItemsRepeater docs

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#29]
In the see also (and maybe the intro description) there should be a link to the ItemsRepeater doc which actually explains how to use this layout: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#uniformgridlayout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6df357f-817e-ffbe-fd16-1efecf8e676f
* Version Independent ID: aef0173a-4e36-f7e3-c0dc-a212b66efa58
* Content: [UniformGridLayout Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.uniformgridlayout?view=winui-2.3)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/UniformGridLayout.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/UniformGridLayout.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by michael-hawker** [comment]
It's also missing on the ItemsRepeater class as well: https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeater

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @michael-hawker. I updated both topics with cross links and more detail.
