### ISSUE TITLE
Documentation Incomplete?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#3]
This doesn't seem to have the same info as the inbox one here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textcommandbarflyout

Is that expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4438107a-5416-cbe3-e17d-381406b6b01e
* Version Independent ID: 8fae7f8a-85db-43c4-2f44-77249b350842
* Content: [TextCommandBarFlyout Class - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.textcommandbarflyout)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.textcommandbarflyout.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.textcommandbarflyout.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Not expected, but the source is in two places so we need to copy from one to the other. @yulikl?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @michael-hawker - This is expected for the WinUI 2.x docs as the CommandBar classes were still inheriting from the WinRT FlyoutBase, so our docs pipeline wasn't pulling in the inherited members. If you switch the WinUI version to 3 preview 3, the inherited members are displayed in-page as expected as https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.flyoutbase?view=winui-3.0-preview has been lifted from WinRT.
