### ISSUE TITLE
Why is the SelectedItem property not a dependency property?

### ISSUE THREAD

**Issue by kaki104** [MicrosoftDocs/winui-api#31]
[Enter feedback here]

Most list-type controls are easy to bind the selected item to the ViewModel with SelectedItem being a dependency property. By the way, I wonder why you added that property as a regular property.

Also, are there any plans to add a SelectionChanged event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc1d2f8-390d-2d68-879e-7da16fb76a99
* Version Independent ID: b2edf06d-ea97-4bfb-a5f9-0eeee78f43cc
* Content: [TreeView Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.treeview?view=winui-2.4)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/TreeView.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/TreeView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by marcelwgn** [comment]
This was recently changed with [this PR on the WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/pull/2523). @Karl-Bridge-Microsoft @ranjeshj @MikeHillberg Would you like me to create a PR to update the documentation in this area?

**Comment by MikeHillberg** [comment]
Yes, thank you!, but, I'm confused about how to coordinate these cross-repo changes. It shouldn't show up in the docs repo until the change in the code repo has released. @ranjeshj, do we have a process for this?

**Comment by marcelwgn** [comment]
I've create the PR to update the documentation in that area, but I am not sure how/when the PR should be merged. Should we wait until 2.5 is released ?

**Comment by ranjeshj** [comment]
The API is currently in preview, so it should show up once we have a 2.5 preview release with that API. @Karl-Bridge-Microsoft Is there some staging we need to do for that or is it okay to do the doc change at any time ?

**Comment by Karl-Bridge-Microsoft** [comment]
The preview release docs are now published and available on the WinUI API site now: https://docs.microsoft.com/en-us/uwp/api/overview/winui/

**Comment by sis2004** [comment]
I updated to the recently published release 2.5.0, and it started saying that SelectedItem is not a dependency property again! It is fine in the latest prerelease **2.5.0-prerelease.201202003** though!

I know it was annotated as [Experimental], but did this functionality get dropped in the official release???

**Comment by marcelwgn** [comment]
The dependency property is still marked as preview as you correctly noted. WinUI 2 stable releases only ship APIs that are not marked as preview, that's why you are getting the error. I'm afraid, until the SelectedItem DP is moved out of preview, you have to use prereleases to use the DP.

**Comment by sis2004** [comment]
Ugh, that sucks! Is there any idea as to why it's still in preview and when it might get moved out of preview?

**Comment by marcelwgn** [comment]
I don't know why it's still in preview it when this will change. @MikeHillberg and @ranjeshj might know more about the plans to move it out of preview.
