### ISSUE TITLE
The link to the sample in the Xaml Control Gallery is broken / there seems to be no sample at all

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/winui-api#36]
The docs page falsely gives the impression that there is a sample for the TwoPaneView in the Xaml Control Gallery by providing a link to open that app. However, inside the app, there is no TwoPaneView sample (https://github.com/microsoft/Xaml-Controls-Gallery/issues/358)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afbb5c-c594-854b-34db-f2cf14dbe646
* Version Independent ID: c6bd4562-9b96-6562-9549-b70bdf7abe73
* Content: [TwoPaneView Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.twopaneview?view=winui-2.4)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/TwoPaneView.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/TwoPaneView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @hansmbakker. Thanks for your feedback. 

We specifically don't mention the TwoPaneView in that block. Instead, we refer to the sample generically (see https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.treeview?view=winui-2.4 for how we specifically refer to a control that does have an example). 

Our primary concern is to consistently provide a link to the sample from every class topic, at a minimum. Even if that particular object doesn't have an example (which is true for a number of classes).

**Comment by hansmbakker** [comment]
Ok, in that case, the request is to have a sample for TwoPaneView in the XAML gallery. Can you please reopen this issue to track this?

**Comment by hansmbakker** [comment]
#please-reopen

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @hansmbakker - I'm afraid this is not a documentation request. You can submit a request through the Issues of the sample itself at https://github.com/microsoft/Xaml-Controls-Gallery.
