### ISSUE TITLE
Nit: Should code sample say C++ instead of CPP on MUXC.Direct page ?

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winui-api#38]
Looking at other code sample, C++ code samples are referenced by `C++`, not CPP. Should the page linked in the document details also use C++ instead of CPP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 353ce7c7-3ad6-f865-37b6-4220d98f33f2
* Version Independent ID: cb986179-4d50-14af-14e6-cfe4d67bb592
* Content: [Microsoft.UI.Xaml.Core.Direct Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.core.direct?view=winui-2.4)
* Content Source: [winui-api-build/xml/ns-Microsoft.UI.Xaml.Core.Direct.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/ns-Microsoft.UI.Xaml.Core.Direct.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic revised.
