### ISSUE TITLE
Wrong image in Container2AnimationStartPosition property

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#39]
The image in the Remarks section shows a ProgressRing, rather than a ProgressBar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe79c5bc-638a-e74b-673a-74b9d4eb54d7
* Version Independent ID: 6b044444-a23f-001f-f1a2-9d0f68dd3636
* Content: [ProgressBarTemplateSettings.Container2AnimationStartPosition Property (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Microsoft.UI.Xaml.Controls.ProgressBarTemplateSettings.Container2AnimationStartPosition?view=winui-2.4)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/ProgressBarTemplateSettings.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/ProgressBarTemplateSettings.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @MikeHillberg - I updated the image to a ProgressBar. The revised topic should be live soon.
