### ISSUE TITLE
API page should link to guidance page

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#4]
Searching for MenuBar was bringing up this API page, but I couldn't easily find the [guidance](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus) page.  We should make sure that these are all dual-linked so people finding via API can get better examples of how to use API if those aren't copied to API page themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9159ebfd-d616-ea5b-e6da-4cb93ca21509
* Version Independent ID: 3fb7b1fb-8376-0a98-dfdc-ef5b95526a22
* Content: [MenuBar Class - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.menubar?view=winui-2.2)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.menubar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.menubar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
Yes! @mijacobs, @mimisasouvanh for visibility

**Comment by jevansaks** [comment]
Is this something we should do manually on each page or is there a way for the doc system to do it more automatically?

**Comment by mijacobs** [comment]
This has to be done manually

**Comment by Karl-Bridge-Microsoft** [comment]
added link
