### ISSUE TITLE
Text is replaced, not inserted.

### ISSUE THREAD

**Issue by MichaelBakkerDP** [MicrosoftDocs/winui-api#40]
The existing text is replaced by the new text. No insertion takes place. Ending with \r or \r\n has no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e650714-c739-1c42-ef89-c7dcc8333483
* Version Independent ID: c82c6e17-3322-63dd-3fbc-b05cacf0fdab
* Content: [RichEditTextDocument.SetText(TextSetOptions, String) Method (Microsoft.UI.Text) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.text.richedittextdocument.settext?view=winui-3.0-preview#Microsoft_UI_Text_RichEditTextDocument_SetText_Microsoft_UI_Text_TextSetOptions_System_String_)
* Content Source: [winui-api-build/xml/Microsoft.UI.Text/RichEditTextDocument.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Text/RichEditTextDocument.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @MichaelBakkerDP - sorry for the delayed response. The topic has been updated.
