### ISSUE TITLE
Missing information on INotifyCollectionChanged for UWP

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#42]
This page describes that the collection in the ItemsSource property can implement the `INotifyCollectionChanged` in the `System.Collections.Specialized` namespace, so that changes to the collection cause an update to the ItemsControl. That's true when running as a Desktop app, but when running as a UWP app the collection must implement the interface from the `Microsoft.UI.Xaml.Interop` namespace. (This is a [known issue](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#known-issues).)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81cf2b8f-9c5b-af44-5e48-09dbb98267f2
* Version Independent ID: 41574435-e339-e5a6-5750-92e0964cbf54
* Content: [ItemsControl.ItemsSource Property (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemscontrol.itemssource?view=winui-3.0-preview#Microsoft_UI_Xaml_Controls_ItemsControl_ItemsSource)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/ItemsControl.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/ItemsControl.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @MikeHillberg - PR has been created and is ready for your review.

**Comment by Karl-Bridge-Microsoft** [comment]
Issue addressed in PR. Waiting for review.
