### ISSUE TITLE
WinUI XmlnsDefinition

### ISSUE THREAD

**Issue by arivoir** [MicrosoftDocs/winui-api#43]
How should the XmlnsDefinition be used in WinUI?

In WPF it can be used like an assembly attribute
`[assembly: XmlnsDefinition("http://XXXXX/winfx/2006/xaml", "XXXX")]
`
But in WinUI is not an attribute. Am I missing something?

**Comment by Karl-Bridge-Microsoft** [comment]
@MikeHillberg - can you help with this?

**Comment by MikeHillberg** [comment]
WinUI doesn't have an equivalent to the XmlnsDefinition attribute. It'd a great proposal on the [repo](https://github.com/microsoft/microsoft-ui-xaml) though.

**Comment by arivoir** [comment]
Thanks for the comment. Will it be added by you?

**Comment by MikeHillberg** [comment]
I'd be happy to open an Issue if you haven't. (I didn't open one already because some people like to open it themselves for tracking purposes.)

**Comment by arivoir** [comment]
Please go ahead. I appreciate it.

**Comment by mrlacey** [comment]
I couldn't find an issue for this. Did one ever get created? Please add a link if it did. :)
