### ISSUE TITLE
Info on localizing would be helpful

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/winui-api#45]
The samples are not localized, probably for clarity to demonstrate the ContentDialog. But some complications with the control might warrant a mention.

A very simple ContentDialog can be expressed in XAML like so:
`<ContentDialog 
    x:name="myDialog" 
    Title="My Title" 
    Content="My text" 
    PrimaryButtonText="OK" 
    SecondaryButtonText="Not OK"
/>`

This can be localized with appropriately named resources:
`<ContentDialog 
    x:name="myDialog" 
    x:Uid="DialogUid"
    Title="My Title" 
    Content="My text" 
    PrimaryButtonText="OK" 
    SecondaryButtonText="Not OK"
/>`

Now you'd have localized resource files with DialogUid.Title, DialogUid.Content, etc. as string identifiers.

The complication comes in when you define a more complex, custom dialog with custom content, like:

`<ContentDialog 
    x:name="myDialog" 
    x:Uid="DialogUid"
    Title="My Title" 
    PrimaryButtonText="OK" 
    SecondaryButtonText="Not OK">
    <StackPanel Orientation="Vertical">
        <TextBlock Text="How do you localize this?" />
        <TextBlock Text="And also this?" />
    </StackPanel>
</ContentDialog>`

You can use DialogUid to localize the title as before, but how do you identify the TextBlocks inside the Content/StackPanel to localize their text? Assigning the TextBlocks their own x:Uids does not seem to work, and assigning an x:Name to each TextBlock and loading them from the code-behind seems messy.

I don't know what the solution is, but it'd be nice if an example on the page provided some guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d762be8-f952-5b02-4797-cf7c47fbb2ab
* Version Independent ID: 043b87f7-53b5-8d96-3312-9547c17c8673
* Content: [ContentDialog Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.contentdialog?view=winui-3.0-preview)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/ContentDialog.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/ContentDialog.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by druske** [comment]
Got the solution worked out; straightforward enough after some sleep. Setting x:Uids for the individual TextBlocks or other controls in the dialog's Content _does_ work, i.e. set `x:Uid="TextBlock1"` and use a string identifier of `"TextBlock1.Text"` in the resource file; I was omitting the ".Text" in the string identifier. So this isn't some unique issue related to the ContentDialog after all, just a tired developer seeing things.

Localization of contained subelements may still be worth a mention or an example, but it isn't critical. You may modify the documentation or close the issue at your own discretion. Sorry for the fire drill.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for following up with an explanation. I'll close this issue for now as we're looking at updating the loc/glob docs for subsequent WinApp SDK releases.
