### ISSUE TITLE
Empty documentation

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/winui-api#48]
This page is missing information. Including, for example, what the boolean return value means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd44162d-1f37-d286-7855-52781229146a
* Version Independent ID: 9f6b9236-1b3a-edff-6c11-549e503b9f7e
* Content: [UIElement.Focus(FocusState) Method (Microsoft.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.focus?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/UIElement.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know, @Marv51. This is a known issue that we're striving to address as we approach the Windows App SDK 1.0 release. I've added details to this topic to address this specific issue.
