### ISSUE TITLE
Api info

### ISSUE THREAD

**Issue by mabbond** [MicrosoftDocs/winui-api#49]
I was reading the API, I think for clarification purposes, you should label that Frame works only in UWP not in Desktop.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4624da95-1d69-74f5-b6c9-882398863720
* Version Independent ID: 578ee248-625e-3d4d-b7df-5d7726372b37
* Content: [Frame Class (Microsoft.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.frame?view=winui-3.0-preview)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/Frame.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/Frame.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jaigak** [comment]
Frame does work in WinUI 3 desktop apps however unlike UWP, the template doesn't create a root frame for you and only creates the window. You can add a frame inside MainWindow.xaml if you want.

**Comment by Karl-Bridge-Microsoft** [comment]
Answered.
