### ISSUE TITLE
MinWideModeWidth doesn't document what the default is

### ISSUE THREAD

**Issue by jevansaks** [MicrosoftDocs/winui-api#5]
Missing the default value here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 612f0ea8-3888-0fe2-046f-1bce5af9eb1a
* Version Independent ID: bd37dd32-d99e-a7c2-fb07-c27a711361e5
* Content: [TwoPaneView.MinWideModeWidth Property - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.twopaneview.minwidemodewidth?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.TwoPaneView.MinWideModeWidth);k(VS.XamlEditor);k(TargetFrameworkMoniker-.NETCore,Version%3Dv5.0)%26rd%3Dtrue&view=winui-2.2)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.twopaneview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.twopaneview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by predavid-zz** [comment]
Working with Jim on the update.

**Comment by jwmsft** [comment]
Doc is updated.
