### ISSUE TITLE
Add pictures of the controls in docs

### ISSUE THREAD

**Issue by galich** [MicrosoftDocs/winui-api#53]
It would be helpful to have a picture of the control in control class docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b18b8b7-c289-0eae-7cd2-0083a0766146
* Version Independent ID: 95e4e595-7a55-e5e4-9c0c-c40be93d114c
* Content: [SplitButton Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.splitbutton?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/SplitButton.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/SplitButton.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @galich - thanks for the feedback. This is something we're actively working on. As you can imagine, it's a bit of an undertaking and does result in a maintenance issue going forward. Most topics do have a link to a corresponding guidance topic that has one or more images of the controls being discussed.
