### ISSUE TITLE
Min/max/close buttons are unclickable

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winui-api#60]
Following the sample code and setting a custom title bar of:

        <StackPanel x:Name="spCustomTitleBar">
            <TextBlock>What a sweet title bar</TextBlock>
        </StackPanel>

Results in the min/max/close buttons being unclickable.

Is there a working sample of Window.SetTitleBar() somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b229bb1-99a0-8bba-fae5-824aa9e9e778
* Version Independent ID: 4189e409-0f1a-f754-bf12-5cbaacd00083
* Content: [Window.SetTitleBar(UIElement) Method (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Thanks for the feedback. This document has been updated with corrected information and a new code example. This paragraph addresses the unclickable buttons:
"The title bar element is presented over the caption buttons, so you should set the side margins of your UIElement to leave space for the caption buttons. (If the title bar element has a transparent background, the caption buttons will show through but will not receive any input.) For example, if all caption buttons (minimize, maximize/restore, and close) are shown on the right side of the window, your title bar element should have a right margin value of 120 to ensure enough space for the buttons."
