### ISSUE TITLE
Wrong statement

### ISSUE THREAD

**Issue by marb2000** [MicrosoftDocs/winui-api#61]
In this statement:
"In a Desktop app you can create each Window explicitly. Creating more than one Window is only supported in Preview versions of WinUI 3."
it says "supported in Preview versions" which is not accurate, it's supported on Experimental versions only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c683f28d-2b9c-0641-3781-4fe778715757
* Version Independent ID: 5ed66529-4e1d-a4b5-4f13-278ed139ff07
* Content: [Window Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0-preview#create-a-new-window)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Being addressed in https://github.com/MicrosoftDocs/winui-api/pull/62
