### ISSUE TITLE
Whose Line Is It Anyway?

### ISSUE THREAD

**Issue by ErichHartmann** [MicrosoftDocs/winui-api#63]
when applicable, suggest a comment is added to the top of example code blocks to indicate the expected files/classes to which the code belongs.

keep in mind the most likely audience, the new and least prepared. ide's provide almost perfect memory reminders for every other experience level.

the wildly confusing name/version soup has already made finding the correct documentation more difficult (e.g. xaml controls gallery or winui controls gallery, etc.). references to those sample applications are unhelpful if the docs example code block does not relate to the sample code.

After a typical search, imagine code examples use the Frame's Source property (i.e. System.Windows.Controls). winui does not have such a property and the winui code examples for it do not use xaml.

explanations and example code blocks should meaningful, stand alone, and directly reference a more fulsome sample. in that way, prerequisites are noted and a simple app can be performed by the audience that reinforces the documentation -- as opposed to a vague reference to a gallery app. galleries make poor sample code because they are built to highlight the controls visual appeal and not as a sample of code in use.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for your feedback! We're constantly striving to improve our dev docs and these are great suggestions. If a full sample exists, we always try to reference that in some way (inline, see also/related links). Many times the full sample does provide code that can be easily snipped and included in a doc. The samples are not typically built by the same team (feature and doc), but we do our best to coordinate. We'll definitely take your suggestions and try to apply them where possible.
