### ISSUE TITLE
Please show me whole example (including library headers(using...)) to make additional window (in another thread)

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/winui-api#64]
[Enter feedback here]
Everyone who may be able to solve the issue but I cannot find out what's libraries should be refer.
I'm sorry for such a beginner's question. What I want is to make additional window in MSToolkit.mvvm pattern. 
I'm using WinsdowsAppSDK 1.0.0 preview3.

I cannot solve;
at https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0-preview#create-a-new-window;
in the last C# sample;
1) "w" of "window.Closed += (_, __) => w.DispatcherQueue.InvokeShutdown();"
2) "DispatcherQueueSyncronizationContext" of "var syncContext = new DispatcherQueueSyncronizationContext();"

Though I've used
using static PInvoke.User32;
or
using static Microsoft.UI.Win32Interop;
those are not solved.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c683f28d-2b9c-0641-3781-4fe778715757
* Version Independent ID: 5ed66529-4e1d-a4b5-4f13-278ed139ff07
* Content: [Window Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0-preview#create-a-new-window)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Due to the age of this issue and the stable release of the WinApp SDK 1.0, along with the subsequent updates to documentation, I'm not sure this issue is still relevant. I'm closing the issue, but please open a new one with more information if this is still a concern.
