### ISSUE TITLE
LaunchActivatedEventArgs.Arguments property is always null

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#67]
This page should say that this property is not supported and always null. (It's only non-null in a UWP app, which is only supported in the 1.0.0-experimental1 release, not 1.0.0-stable).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b6986a0-a2dc-e277-7b70-5b81a941ea2b
* Version Independent ID: 9375bdc8-cf6c-6978-c286-f1ae88f2a64a
* Content: [LaunchActivatedEventArgs.Arguments Property (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.launchactivatedeventargs.arguments?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/LaunchActivatedEventArgs.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/LaunchActivatedEventArgs.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been updated.
