### ISSUE TITLE
SetTitleBar examples are not helpful

### ISSUE THREAD

**Issue by dedaap72** [MicrosoftDocs/winui-api#69]
The examples are not very helpful.
The XAML defined TitleBar called `CustomTitleBar` is protected by default in the `Window` where it is defined, so to make the code in `App` work a public getter is needed to expose it from the `Window`.
Also, once that is done, using a `TextBlock` as in the example renders the window buttons inoperable. They (sometimes) light up when hovering over them with the mouse, but cannot be clicked, probably because the `TextBlock` lies on top of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b229bb1-99a0-8bba-fae5-824aa9e9e778
* Version Independent ID: 4189e409-0f1a-f754-bf12-5cbaacd00083
* Content: [Window.SetTitleBar(UIElement) Method (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Thanks for the feedback. This document has been updated with corrected information and a new code example.
