### ISSUE TITLE
More information available

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#7]
There's a good description and code example for this class on the page for the GroupName property. It would be better to hoist that up to the class page, and then there could be a reference to it from the property page.

There's also a good short description of this class in the [Spec](https://github.com/Microsoft/microsoft-ui-xaml-specs/pull/15) which would be good to add here:

* A radio menu flyout item is a menu item that is mutually exclusive with other radio menu items in its group. This control contol allows you to present users with menus containing multiple options, where a user would choose only one of these options at a given time.
* RadioMenuFlyoutItem can be added into a MenuBarItem, MenuFlyout, or MenuFlyoutSubItem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e856697d-d920-4f04-47f3-34a45269c891
* Version Independent ID: 1b916452-b3f8-b225-13ba-4d39587be8e1
* Content: [RadioMenuFlyoutItem Class - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.radiomenuflyoutitem?view=winui-2.2)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.radiomenuflyoutitem.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.radiomenuflyoutitem.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
Fixed.
