### ISSUE TITLE
Hyperlink broken

### ISSUE THREAD

**Issue by duanqn** [MicrosoftDocs/winui-api#72]
"OnLaunched" link is broken in the "OnLaunched" paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c683f28d-2b9c-0641-3781-4fe778715757
* Version Independent ID: 5ed66529-4e1d-a4b5-4f13-278ed139ff07
* Content: [Window Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The link to OnLaunched has been fixed.
