### ISSUE TITLE
Error applying SystemInputCursor to ProtectedCursor property of custom control

### ISSUE THREAD

**Issue by MichaelBakker** [MicrosoftDocs/winui-api#73]
I am trying to have a ToggleButton with a hand as a cursor. Based on available documentation i came up with this:
```
/// <summary>
/// Custom <see cref="ToggleButton"/> that has a hand for a cursor.
/// </summary>
public sealed class CustomToggleButton : ToggleButton
{
	public CustomToggleButton() : base()
	{
		try
		{
			InputCursor crs = InputSystemCursor.Create(InputSystemCursorShape.Hand); // no problem
			ProtectedCursor = crs; // read access violation here
		}
		catch { }
	}
}
```

Error details:
Exception thrown at 0x00007FFAC78B93F3 (Microsoft.ui.xaml.dll) in MyAttemptAtGreatness.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Upon setting the ProtectedCursor property i get an access violation error. What am i missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5466f5c-2696-dde0-be06-ef528a584900
* Version Independent ID: 014bbe3e-eb01-576e-e2b5-8ca50d505840
* Content: [InputSystemCursor.Create(InputSystemCursorShape) Method (Microsoft.UI.Input) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.input.inputsystemcursor.create?view=winui-3.0#Microsoft_UI_Input_InputSystemCursor_Create_Microsoft_UI_Input_InputSystemCursorShape_)
* Content Source: [winui-api-build/xml/Microsoft.UI.Input/InputSystemCursor.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Input/InputSystemCursor.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
You might find your answer at https://github.com/microsoft/WindowsAppSDK/discussions/1816.
