### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by ritesh3103** [MicrosoftDocs/winui-api#75]
The example given on this page cannot work as the textblock is inside grid.

m_window.CustomTitleBar gives error.

I wrote the code as given below:

`protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {
            m_window = new MainWindow();

            m_window.ExtendsContentIntoTitleBar = true;
            Grid CGrd = m_window.Content as Grid;
if (CGrd != null)
{
            UIElement Elem = CGrd.Children[0];
            m_window.SetTitleBar(Elem);
}
            m_window.Activate();

        }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b229bb1-99a0-8bba-fae5-824aa9e9e778
* Version Independent ID: 4189e409-0f1a-f754-bf12-5cbaacd00083
* Content: [Window.SetTitleBar(UIElement) Method (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0#Microsoft_UI_Xaml_Window_SetTitleBar_Microsoft_UI_Xaml_UIElement_)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Window.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Window.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Thanks for the feedback. This document has been updated with corrected information and a new code example.
