### ISSUE TITLE
The DispatcherQueuePriority Enum Fields table has missing and incorrect information

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#76]
The DispatcherQueuePriority Enum Fields table has missing and incorrect information.

![Screenshot 2022-01-06 080357](https://user-images.githubusercontent.com/5379488/148387236-6b304cf5-8db9-425c-84d9-cb115e35ca33.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf1425-b66f-3558-efca-73f1a4a87449
* Version Independent ID: d284b12f-0486-3110-0c00-0113a48e51bc
* Content: [DispatcherQueuePriority Enum (Microsoft.UI.Dispatching) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.dispatching.dispatcherqueuepriority?view=winui-3.0&source=docs#feedback)
* Content Source: [winui-api-build/xml/Microsoft.UI.Dispatching/DispatcherQueuePriority.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Dispatching/DispatcherQueuePriority.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been updated. Thanks!
