### ISSUE TITLE
Clarify automatic behavior

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winui-api#77]
> [Some members] will **not** be invoked when running in a desktop app

Not true. They will not be invoked _automatically_ by the OS, but one is free to implement user code that invokes those members as appropriate. I would appreciate it if you could clarify this. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee420720-e2d3-270c-5875-22e4e14e7e7a
* Version Independent ID: a444eee6-7f81-c1d4-7f03-dc0c40a37ebc
* Content: [Application Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.application?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/Application.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/Application.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! Topic has been updated.
