### ISSUE TITLE
The Microsoft.Graphics link on /windows/winui/api/ doesn't work

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#78]
As per the title, two links are broken here:

https://docs.microsoft.com/en-us/windows/winui/api/

* Microsoft.Graphics
* Microsoft.System

Likely because no top-level namespace pages were created/transferred for them.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. This is a known issue with our doc build system. It's being worked on. No ETA.
