### ISSUE TITLE
Frame.NavigateToType link is broken on microsoft.ui.xaml.navigation.framenavigationoptions page

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#80]
As per the title, the `Frame.NavigateToType` link at the bottom of the page is broken on the `microsoft.ui.xaml.navigation.framenavigationoptions` page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42eb7277-7b05-6e9b-a029-0263f7a9b64f
* Version Independent ID: dfeea3eb-166b-5e5c-adcb-1069d05cee9f
* Content: [FrameNavigationOptions Class (Microsoft.UI.Xaml.Navigation) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.navigation.framenavigationoptions?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Navigation/FrameNavigationOptions.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Navigation/FrameNavigationOptions.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The link is fixed now.
