### ISSUE TITLE
Microsoft.ui.xaml.frameworkelement.actualheight has a broken link under the See also section

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#81]
As per the title, the See also link on this page has a link that just reads:

* \<xref:Microsoft.UI.Xaml.FrameworkElement.SizeChanged%0a(frameworkelement_sizechanged.md)\>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b692d535-675b-ed29-bf89-e93d8287a5c0
* Version Independent ID: 90cf82dd-0783-e60a-8ba6-a918e46048ed
* Content: [FrameworkElement.ActualHeight Property (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.frameworkelement.actualheight?view=winui-3.0#microsoft-ui-xaml-frameworkelement-actualheight)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/FrameworkElement.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/FrameworkElement.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been updated. Thanks!
