### ISSUE TITLE
microsoft.ui.xaml.media.brush page has a broken link under "Brushes as XAML resource"

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#82]
As per the title, this page has a broken link under "Brushes as XAML resource" that just reads:

> @"Microsoft.UI.Xaml.Media.SolidColorBrush?text=SolidColorBrush"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a8ba49-ddd0-2f3b-440e-c985068ad3bb
* Version Independent ID: a5812271-11ba-9a29-daa5-ff969de14dca
* Content: [Brush Class (Microsoft.UI.Xaml.Media) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.brush?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Media/Brush.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Media/Brush.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks, topic has been updated.
