### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by teohumeau** [MicrosoftDocs/winui-api#85]
The link to the AnimatedIcon page sends to 404 error.
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d2e09a5a-b2fa-7f6d-c6d7-d476dbeb3c3a
* Version Independent ID: ce2360d4-1877-93ae-99bf-7d547e1e5c25
* Content: [NavigationViewItem.Icon Property (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/fr-fr/windows/winui/api/microsoft.ui.xaml.controls.navigationviewitem.icon?f1url=%3FappId%3DDev16IDEF1%26l%3DFR-FR%26k%3Dk(Microsoft.UI.Xaml.Controls.NavigationViewItem.Icon);k(VS.XamlEditor);k(TargetFrameworkMoniker-.NETCore,Version%253Dv5.0)%26rd%3Dtrue&view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/NavigationViewItem.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/NavigationViewItem.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. The topic has been updated.
