### ISSUE TITLE
XamlUICommand.KeyboardAccelerators documentation whoops

### ISSUE THREAD

**Issue by blake-fm** [MicrosoftDocs/winui-api#86]
"Gets or sets the collection [...]" - there is no (longer a?) set accessor on the KeyboardAccelerators property, in Windows App SDK 1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4396d74c-76c4-724d-8eee-07f3f3d7b66f
* Version Independent ID: caaadbc6-785e-ebf6-88b9-4ca8787aecac
* Content: [XamlUICommand.KeyboardAccelerators Property (Microsoft.UI.Xaml.Input) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.xamluicommand.keyboardaccelerators?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Input/XamlUICommand.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Input/XamlUICommand.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. Topic has been updated.
