### ISSUE TITLE
Content very long, could use an abbreviated list

### ISSUE THREAD

**Issue by mstasak** [MicrosoftDocs/winui-api#87]
This is a very long list of properties and methods.  I think a simple filter switch, such as "common" / "complete" could make this and similar pages much more useful?  Or perhaps a checkbox to hide inherited, ubiquitous members?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01539533-ca9f-5851-b5a8-05a95c3f4f8c
* Version Independent ID: fa2040e4-5404-a85e-1a76-021b258ec38e
* Content: [DropDownButton Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.dropdownbutton?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.DropDownButton);k(VS.XamlEditor)%26rd%3Dtrue&view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/DropDownButton.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/DropDownButton.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. We're always looking to improve the end-user experience with the API docs and the member lists on the Class topics is always in the discussion. At this time, our engineering process for building API topics require that all members (including inherited) be listed on those pages.

The primary TOC only shows direct members.
