### ISSUE TITLE
No mention of x:DataType in DataTemplate class documentation

### ISSUE THREAD

**Issue by XamlBrewer** [MicrosoftDocs/winui-api#88]
[Enter feedback here]
The DataTemplate documentation should contain a description or at least a reference to x:DataType.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8ad7d0-abd5-a800-2a48-b98faa911f42
* Version Independent ID: cf0fdf5d-d039-e84c-36d3-f2fbcb62c498
* Content: [DataTemplate Class (Microsoft.UI.Xaml) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.datatemplate?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml/DataTemplate.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml/DataTemplate.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi, thanks for the feedback. 

I found two links to https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-in-depth, which does cover x:DataType. 

One link is in the paragraph preceding the first example and the second is in the last paragraph of the remarks.
