### ISSUE TITLE
Broken image link under Examples

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#89]
Per the title, there is a broken image link under the examples section:

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.scaletransform?view=winui-3.0#examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a0f1c8-d633-c873-ced8-5981b571c897
* Version Independent ID: 076e2e7c-fa65-753e-4cdf-59689fe1a34e
* Content: [ScaleTransform Class (Microsoft.UI.Xaml.Media) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.scaletransform?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Media/ScaleTransform.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Media/ScaleTransform.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. This appears to be a backend issue. A bug has been logged against engineering.

**Comment by Karl-Bridge-Microsoft** [comment]
Issue has been resolved.
