### ISSUE TITLE
Missing reference to samples gallery

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winui-api#9]
The [TreeView](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.TreeView) control in the Windows.UI.Xaml.Controls namespace has a reference to the TreeView [how-to](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view) and to the [samples gallery](https://github.com/Microsoft/Xaml-Controls-Gallery). Those references should be on this page too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc1d2f8-390d-2d68-879e-7da16fb76a99
* Version Independent ID: b2edf06d-ea97-4bfb-a5f9-0eeee78f43cc
* Content: [TreeView Class - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Microsoft.UI.Xaml.Controls.TreeView?view=winui-2.2)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winui-api-build?path=%2fwinui-api-build%2fmicrosoft.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
added link.
