### ISSUE TITLE
Many broken links can be found in the WinUI docs via a search

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#91]
I keep finding broken links in the WinUI docs. Rather than reporting them individually I'll share a search query that indicates 91 pages have broken links:

[Broken link search](https://www.google.com/search?q=%22\(%40%22+site:docs.microsoft.com/en-us/windows/winui)

Unsure how the docs are built - if this is a one-time translation error or a bug that will cause reoccurring broken links in the future.

If one-time then I guess it is just a task of visiting each search result, CTRL+F for "(@", and manually applying fixes to all occurrences.

*Note: after traversing 3-4 pages the link at the bottom needs to be used to see more results: 

> If you like, you can repeat the search with the omitted results included.

@Karl-Bridge-Microsoft

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kmgallahan - this is definitely a bug in our build system. I've logged an issue with our engineering team.

**Comment by kmgallahan** [comment]
@Karl-Bridge-Microsoft It appears the underlying issue here may have been resolved?

**Comment by Karl-Bridge-Microsoft** [comment]
It appears so. Sorry for the looooong delay in resolving it. There's still a minor formatting issue, but the links appear to be rendering correctly now. I'll close this issue, but please open a new one if required.
