### ISSUE TITLE
DependencyObject.ClearValue link not found

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winui-api#92]
Title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acd9840-42dc-962a-d5ac-7d4b3436206a
* Version Independent ID: 2845d546-1199-a282-2823-42465317aa7f
* Content: [Binding Class (Microsoft.UI.Xaml.Data) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.data.binding?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Data/Binding.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Data/Binding.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. Link should be fixed now.
