### ISSUE TITLE
The WinUI 3 Blank App template doesn't create an App.xaml.cs as suggested.

### ISSUE THREAD

**Issue by AlanPBourke** [MicrosoftDocs/winui-api#94]
[Enter feedback here]

The text in the Examples section states:

_The following code example shows an abridged version (except for the [C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt) version, which lists the full function) of the [OnLaunched](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.onlaunched(windows.applicationmodel.activation.launchactivatedeventargs)) method override generated for the Blank App template in Visual Studio._

However the WinUI 3 Blank App template doesn't create an App.xaml.cs with any reference to frames, just a MainWindow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5c220e6-124a-09df-1b63-442657a9796b
* Version Independent ID: 6849a14f-ed3e-308f-ea41-66cf223f64c4
* Content: [Page Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.page?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/Page.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/Page.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Thanks, @AlanPBourke, I've updated that Examples section for WinUI 3 (previously it still had the UWP info and code in there). There's also a bit of information about the difference between the WinUI 3 and UWP project templates, with respect to navigation, in [Do I need to implement page navigation?](https://docs.microsoft.com/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3#do-i-need-to-implement-page-navigation).

-Steve
