### ISSUE TITLE
LaunchActivatedEventArgs dosen't have PreviousExecutionState property

### ISSUE THREAD

**Issue by felinepunch** [MicrosoftDocs/winui-api#96]
[Enter feedback here]
"if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)" in OnLaunched method, e(type LaunchActivatedEventArgs) dose not have PreviousExecutionState property. So compile error is occured.

And I comment out if statement, OnLaunched method throws exception because Window.Current is null.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4624da95-1d69-74f5-b6c9-882398863720
* Version Independent ID: 578ee248-625e-3d4d-b7df-5d7726372b37
* Content: [Frame Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.frame?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/Frame.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/Frame.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The UWP code has been removed from the Frame class for WinUI 3 and the documentation updated.
