### ISSUE TITLE
Messed up link in "Processing input on background threads" section

### ISSUE THREAD

**Issue by daves561** [MicrosoftDocs/winui-api#97]
The section "Processing input on background threads" attempts to link to the `CreateCoreIndependentInputSource` method, but instead of linking to it, the formatting is a bit messed up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17e52bf-c18c-53a8-bda6-ae59b74145cc
* Version Independent ID: 95a936f0-8d68-a563-ef72-32baa6dd5515
* Content: [SwapChainPanel Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.swapchainpanel?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/SwapChainPanel.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/SwapChainPanel.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @daves561. This link is fixed.
