### ISSUE TITLE
IsSticky link is broken

### ISSUE THREAD

**Issue by krschau** [MicrosoftDocs/winui-api#98]
The link to the IsSticky property is broken in this page. It's also broken in the Windows.UI.Xaml version: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CommandBar?view=winrt-22000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca675191-8597-c844-34e9-6855805c6e45
* Version Independent ID: 37222423-3232-c763-9e7e-d10ee6b687bc
* Content: [CommandBar Class (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.commandbar?view=winui-3.0&source=docs#placement)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/CommandBar.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/CommandBar.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
I checked all the IsSticky links, and they all worked for me. Please re-open this issue if you still see a problem.
