### ISSUE TITLE
XAML Navigation sample doesn't exist

### ISSUE THREAD

**Issue by krschau** [MicrosoftDocs/winui-api#99]
The link for [XAML Navigation sample](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/XamlNavigation) points towards two deprecated pages before you get to a valid sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e2b91c4-7258-c42d-a055-e9ce3a4f7e14
* Version Independent ID: 4ea28732-b9a4-8886-07d7-6cb36b3282be
* Content: [Page.TopAppBar Property (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.page.topappbar?view=winui-3.0)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/Page.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/Page.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks! The invalid link was removed when the page was updated.
